language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=evegenie egtest.py
branches:
  only:
    - /.*/
after_success:
  coveralls
