language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=evegenie python -m pytest egtest.py
after_success:
  coveralls
